[package]
name = "flood"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.5" }
gif = {version = "0.12.0"}
termcolor = { version = "1.1.3" }
regex = { version = "1.7.0" }